[serial.command]
port = "/dev/ttyUSB0"
baudrate = 115200
timeout = 0.05

[serial.telemetry]
port = "/dev/ttyACM0"
baudrate = 115200
timeout = 0.05

[remote.speed_profiles]
forward = [-4000, 4000, 4000, -4000]
backward = [4000, -4000, -4000, 4000]
left = [-2000, 1500, 4500, -5000]
right = [-4500, 5000, 2000, -1500]
stop = [0, 0, 0, 0]
