[serial.command]
port = "/dev/ttyUSB0"
baudrate = 115200
timeout = 0.05

[serial.telemetry]
port = "/dev/ttyACM0"
baudrate = 115200
timeout = 0.05

[remote.speed_profiles]
forward = [-5000, 5000, 5000, -5000]
backward = [5000, -5000, -5000, 5000]
left = [-1000, 1500, 5500, -5500]
right = [-5500, 5500, 1000, -1500]
stop = [0, 0, 0, 0]
